name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        if: github.event_name == 'release'
        run: |
          TAG=$(basename ${{ github.ref }})
          sed -i "s/const Version = \"\"/const Version = \"${TAG}\"/g" ./core/version.go
      - name: Build and release
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          compress_assets: false