name: Deploy Wiki

on:
  push:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          path: wiki/